<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $pages = [
            ['controller' => 'Home', 'method' => 'index', 'menu_controller' => 'home', 'menu_method' => 'index', 'page_name' => 'Home', 'notes' => '<p>Página inicial do sistema administrativo.</p>', 'is_public' => false, 'icon' => 'fas fa-home', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'Usuarios', 'method' => 'listar', 'menu_controller' => 'usuarios', 'menu_method' => 'listar', 'page_name' => 'Usuários', 'notes' => '<p>Página para listar os usuários.</p>', 'is_public' => false, 'icon' => 'fas fa-users', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'Login', 'method' => 'acesso', 'menu_controller' => 'login', 'menu_method' => 'acesso', 'page_name' => 'Acesso', 'notes' => '<p>Página de login.</p>', 'is_public' => true, 'icon' => '', 'page_group_id' => 7, 'is_active' => true],
            ['controller' => 'Login', 'method' => 'logout', 'menu_controller' => 'login', 'menu_method' => 'logout', 'page_name' => 'Sair', 'notes' => '<p>Página para sair do administrativo.</p>', 'is_public' => true, 'icon' => '', 'page_group_id' => 7, 'is_active' => true],
            ['controller' => 'NovoUsuario', 'method' => 'novoUsuario', 'menu_controller' => 'novo-usuario', 'menu_method' => 'novo-usuario', 'page_name' => 'Novo Usuário', 'notes' => '<p>Página para cadastrar novo usuário na pagina de login.</p>', 'is_public' => true, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'Confirmar', 'method' => 'confirmarEmail', 'menu_controller' => 'confirmar', 'menu_method' => 'confirmar-email', 'page_name' => 'Confirmar e-mail', 'notes' => '<p>Página para confirmar e-mail.</p>', 'is_public' => true, 'icon' => '', 'page_group_id' => 7, 'is_active' => true],
            ['controller' => 'EsqueceuSenha', 'method' => 'esqueceuSenha', 'menu_controller' => 'esqueceu-senha', 'menu_method' => 'esqueceu-senha', 'page_name' => 'Esqueceu a senha', 'notes' => '<p>Página para recuperar a senha.</p>', 'is_public' => true, 'icon' => '', 'page_group_id' => 7, 'is_active' => true],
            ['controller' => 'AtualSenha', 'method' => 'atualSenha', 'menu_controller' => 'atual-senha', 'menu_method' => 'atual-senha', 'page_name' => 'Atualizar a senha', 'notes' => '<p>Página para atualizar a senha.</p>', 'is_public' => true, 'icon' => '', 'page_group_id' => 7, 'is_active' => true],
            ['controller' => 'VerPerfil', 'method' => 'perfil', 'menu_controller' => 'ver-perfil', 'menu_method' => 'perfil', 'page_name' => 'Ver Perfil', 'notes' => '<p>Página para o usuário ver o seu perfil.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'AlterarSenha', 'method' => 'altSenha', 'menu_controller' => 'alterar-senha', 'menu_method' => 'alt-senha', 'page_name' => 'Alterar Senha', 'notes' => '<p>Página para o próprio usuário alterar a sua senha.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'EditarPerfil', 'method' => 'altPerfil', 'menu_controller' => 'editar-perfil', 'menu_method' => 'alt-perfil', 'page_name' => 'Editar Perfil', 'notes' => '<p>Página para o próprio usuário editar os dados do seu perfil.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'VerUsuario', 'method' => 'verUsuario', 'menu_controller' => 'ver-usuario', 'menu_method' => 'ver-usuario', 'page_name' => 'Ver Usuário', 'notes' => '<p>Página para ver detalhes do usuário.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'EditarSenha', 'method' => 'editSenha', 'menu_controller' => 'editar-senha', 'menu_method' => 'edit-senha', 'page_name' => 'Editar Senha', 'notes' => '<p>Página para o administrador altera a senha do usuário.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'EditarUsuario', 'method' => 'editUsuario', 'menu_controller' => 'editar-usuario', 'menu_method' => 'edit-usuario', 'page_name' => 'Editar Usuário', 'notes' => '<p>Página para editar os dados do usuário.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'CadastrarUsuario', 'method' => 'cadUsuario', 'menu_controller' => 'cadastrar-usuario', 'menu_method' => 'cad-usuario', 'page_name' => 'Cadastrar Usuário', 'notes' => '<p>Página para cadastrar novo usuário.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'ApagarUsuario', 'method' => 'apagarUsuario', 'menu_controller' => 'apagar-usuario', 'menu_method' => 'apagar-usuario', 'page_name' => 'Apagar Usuário', 'notes' => '<p>Página para apagar usuário.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 4, 'is_active' => true],
            ['controller' => 'NivelAcesso', 'method' => 'listar', 'menu_controller' => 'nivel-acesso', 'menu_method' => 'listar', 'page_name' => 'Nível de Acesso', 'notes' => '<p>Página para listar nível de acesso.</p>', 'is_public' => false, 'icon' => 'fas fa-key', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'CadastrarNivAc', 'method' => 'cadNivAc', 'menu_controller' => 'cadastrar-niv-ac', 'menu_method' => 'cad-niv-ac', 'page_name' => 'Cadastrar ní­vel de Acesso', 'notes' => '<p>Página para cadastrar nível de acesso.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'VerNivAc', 'method' => 'VerNivAc', 'menu_controller' => 'ver-niv-ac', 'menu_method' => 'ver-niv-ac', 'page_name' => 'Detalhes do Ní­vel de Acesso', 'notes' => '<p>Página para ver detalhes do ní­vel de acesso.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'EditarNivAc', 'method' => 'editNivAc', 'menu_controller' => 'editar-niv-ac', 'menu_method' => 'edit-niv-ac', 'page_name' => 'Editar Nível de Acesso', 'notes' => '<p>Página para editar nível de acesso.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'ApagarNivAc', 'method' => 'apagarNivAc', 'menu_controller' => 'apagar-niv-ac', 'menu_method' => 'apagar-niv-ac', 'page_name' => 'Apagar Nível de Acesso', 'notes' => '<p>Página para apagar nível de acesso.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 4, 'is_active' => true],
            ['controller' => 'AltOrdemNivAc', 'method' => 'altOrdemNivAc', 'menu_controller' => 'alt-ordem-niv-ac', 'menu_method' => 'alt-ordem-niv-ac', 'page_name' => 'Alterar ordem nível de acesso', 'notes' => '<p>Página para alterar ordem do nível de acesso.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 6, 'is_active' => true],
            ['controller' => 'Pagina', 'method' => 'listar', 'menu_controller' => 'pagina', 'menu_method' => 'listar', 'page_name' => 'Listar Páginas', 'notes' => '<p>Página para listar as paginas do administrativo.</p>', 'is_public' => false, 'icon' => 'fas fa-file-alt', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'CadastrarPagina', 'method' => 'cadPagina', 'menu_controller' => 'cadastrar-pagina', 'menu_method' => 'cad-pagina', 'page_name' => 'Cadastrar Página', 'notes' => '<p>Formulário para cadastrar página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'VerPagina', 'method' => 'verPagina', 'menu_controller' => 'ver-pagina', 'menu_method' => 'ver-pagina', 'page_name' => 'Visualizar Página', 'notes' => '<p>Página para ver detalhes da página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'EditarPagina', 'method' => 'editPagina', 'menu_controller' => 'editar-pagina', 'menu_method' => 'edit-pagina', 'page_name' => 'Editar Página', 'notes' => '<p>Formulário para editar a página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'ApagarPagina', 'method' => 'apagarPagina', 'menu_controller' => 'apagar-pagina', 'menu_method' => 'apagar-pagina', 'page_name' => 'Apagar Página', 'notes' => '<p>Página para apagar página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 4, 'is_active' => true],
            ['controller' => 'Permissoes', 'method' => 'listar', 'menu_controller' => 'permissoes', 'menu_method' => 'listar', 'page_name' => 'Permissão', 'notes' => '<p>Página para listar as permissões do nível de acesso.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'LibPermi', 'method' => 'libPermi', 'menu_controller' => 'lib-permi', 'menu_method' => 'lib-permi', 'page_name' => 'Liberar Permissão', 'notes' => '<p>Página para liberar permissão.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'LibMenu', 'method' => 'libMenu', 'menu_controller' => 'lib-menu', 'menu_method' => 'lib-menu', 'page_name' => 'Liberar no menu', 'notes' => '<p>Página para liberar ou bloquear a página no menu.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'LibDropdown', 'method' => 'libDropdown', 'menu_controller' => 'lib-dropdown', 'menu_method' => 'lib-dropdown', 'page_name' => 'Liberar Dropdown', 'notes' => '<p>Página para liberar ou bloquear a página a ser apresentado como dropdown no menu.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'AltOrdemMenu', 'method' => 'altOrdemMenu', 'menu_controller' => 'alt-ordem-menu', 'menu_method' => 'alt-ordem-menu', 'page_name' => 'Alterar Ordem Menu', 'notes' => '<p>Página para alterar a ordem das páginas no menu.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'SincroPgNivAc', 'method' => 'sincroPgNivAc', 'menu_controller' => 'sincro-pg-niv-ac', 'menu_method' => 'sincro-pg-niv-ac', 'page_name' => 'Sincronizar Permissões', 'notes' => '<p>Página para sincronizar as permissões de acesso a cada nível de acesso para as páginas do sistema.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'EditarNivAcPgMenu', 'method' => 'editNivAcPgMenu', 'menu_controller' => 'editar-niv-ac-pg-menu', 'menu_method' => 'edit-niv-ac-pg-menu', 'page_name' => 'Editar Item de Menu da Página', 'notes' => '<p>Formulário para editar o item de menu que a página pertence para um determinado nível de acesso.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'Menu', 'method' => 'listar', 'menu_controller' => 'menu', 'menu_method' => 'listar', 'page_name' => 'Itens de Menu', 'notes' => '<p>Listar os itens do menu.</p>', 'is_public' => false, 'icon' => 'fab fa-elementor', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'CadastrarMenu', 'method' => 'cadMenu', 'menu_controller' => 'cadastrar-menu', 'menu_method' => 'cad-menu', 'page_name' => 'Cadastrar Item de Menu', 'notes' => '<p>Formulário para cadastrar item de menu.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'VerMenu', 'method' => 'verMenu', 'menu_controller' => 'ver-menu', 'menu_method' => 'ver-menu', 'page_name' => 'Ver item de menu', 'notes' => '<p>Página para ver detalhes do item de menu.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'EditarMenu', 'method' => 'editMenu', 'menu_controller' => 'editar-menu', 'menu_method' => 'edit-menu', 'page_name' => 'Editar item de menu', 'notes' => '<p>Formulário para editar o item de menu.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'ApagarMenu', 'method' => 'apagarMenu', 'menu_controller' => 'apagar-menu', 'menu_method' => 'apagar-menu', 'page_name' => 'Apagar Item de Menu', 'notes' => '<p>Página para apagar item de menu.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 4, 'is_active' => true],
            ['controller' => 'AltOrdemItemMenu', 'method' => 'altOrdemItemMenu', 'menu_controller' => 'alt-ordem-item-menu', 'menu_method' => 'alt-ordem-item-menu', 'page_name' => 'Alterar Ordem Item de Menu', 'notes' => '<p>Página para alterar a ordem do itens no menu.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'EditarFormCadUsuario', 'method' => 'editFormCadUsuario', 'menu_controller' => 'editar-form-cad-usuario', 'menu_method' => 'edit-form-cad-usuario', 'page_name' => 'Cadastro de Login', 'notes' => '<p>Formulário para editar as informações do formulário cadastrar usuário na página de login.</p>', 'is_public' => false, 'icon' => 'fas fa-edit', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'EditarConfEmail', 'method' => 'editConfEmail', 'menu_controller' => 'editar-conf-email', 'menu_method' => 'edit-conf-email', 'page_name' => 'Configuração de E-mail', 'notes' => '<p>Formulário para editar as configuração do servidor de envio de e-mail.</p>', 'is_public' => false, 'icon' => 'fas fa-at', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'Cor', 'method' => 'listar', 'menu_controller' => 'cor', 'menu_method' => 'listar', 'page_name' => 'Cores', 'notes' => '<p>Listar as cores dos botões.</p>', 'is_public' => false, 'icon' => 'fas fa-tint', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'VerCor', 'method' => 'verCor', 'menu_controller' => 'ver-cor', 'menu_method' => 'ver-cor', 'page_name' => 'Ver Cores', 'notes' => '<p>Página para ver detalhes da cor do botão.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'EditarCor', 'method' => 'editCor', 'menu_controller' => 'editar-cor', 'menu_method' => 'edit-cor', 'page_name' => 'Editar a Cor', 'notes' => '<p>Formulário para editar as cores dos botões.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'CadastrarCor', 'method' => 'cadCor', 'menu_controller' => 'cadastrar-cor', 'menu_method' => 'cad-cor', 'page_name' => 'Cadastrar Cor', 'notes' => '<p>Formulário para cadastrar a cor do botão.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'ApagarCor', 'method' => 'apagarCor', 'menu_controller' => 'apagar-cor', 'menu_method' => 'apagar-cor', 'page_name' => 'Apagar a Cor', 'notes' => '<p>Página para apagar a cor do botão.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 4, 'is_active' => true],
            ['controller' => 'GrupoPg', 'method' => 'listar', 'menu_controller' => 'grupo-pg', 'menu_method' => 'listar', 'page_name' => 'Grupo de Página', 'notes' => '<p>Listar os grupos das páginas.</p>', 'is_public' => false, 'icon' => 'fas fa-file-alt', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'VerGrupoPg', 'method' => 'verGrupoPg', 'menu_controller' => 'ver-grupo-pg', 'menu_method' => 'ver-grupo-pg', 'page_name' => 'Ver Grupo de Página', 'notes' => '<p>Página para ver detalhes do grupo de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'CadastrarGrupoPg', 'method' => 'cadGrupoPg', 'menu_controller' => 'cadastrar-grupo-pg', 'menu_method' => 'cad-grupo-pg', 'page_name' => 'Cadastro Grupo de Página', 'notes' => '<p>Formulário para cadastrar novo grupo de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'EditarGrupoPg', 'method' => 'editGrupoPg', 'menu_controller' => 'editar-grupo-pg', 'menu_method' => 'edit-grupo-pg', 'page_name' => 'Editar Grupo de Página', 'notes' => '<p>Formulário para editar os dados do grupo de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'ApagarGrupoPg', 'method' => 'apagarGrupoPg', 'menu_controller' => 'apagar-grupo-pg', 'menu_method' => 'apagar-grupo-pg', 'page_name' => 'Apagar Grupo de Página', 'notes' => '<p>Página para apagar grupo de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 4, 'is_active' => true],
            ['controller' => 'AltOrdemGrupoPg', 'method' => 'altOrdemGrupoPg', 'menu_controller' => 'alt-ordem-grupo-pg', 'menu_method' => 'alt-ordem-grupo-pg', 'page_name' => 'Alterar Ordem Grupo Página', 'notes' => '<p>Altera a ordem do grupo de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'TipoPg', 'method' => 'listar', 'menu_controller' => 'tipo-pg', 'menu_method' => 'listar', 'page_name' => 'Tipo de Página', 'notes' => '<p>Listar os tipos de páginas.</p>', 'is_public' => false, 'icon' => 'fas fa-list-ol', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'CadastrarTipoPg', 'method' => 'cadTipoPg', 'menu_controller' => 'cadastrar-tipo-pg', 'menu_method' => 'cad-tipo-pg', 'page_name' => 'Cadastrar Tipo de Página', 'notes' => '<p>Formulário para cadastrar o tipo de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'EditarTipoPg', 'method' => 'editTipoPg', 'menu_controller' => 'editar-tipo-pg', 'menu_method' => 'edit-tipo-pg', 'page_name' => 'Editar Tipo de Página', 'notes' => '<p>Formulário para editar o tipo de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'VerTipoPg', 'method' => 'verTipoPg', 'menu_controller' => 'ver-tipo-pg', 'menu_method' => 'ver-tipo-pg', 'page_name' => 'Ver Tipo de Página', 'notes' => '<p>Página para ver detalhes do tipo de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'ApagarTipoPg', 'method' => 'apagarTipoPg', 'menu_controller' => 'apagar-tipo-pg', 'menu_method' => 'apagar-tipo-pg', 'page_name' => 'Apagar Tipo de Página', 'notes' => '<p>Página para apagar o tipo de página.</p>', 'is_public' => false, 'icon' => 'fas fa-trash-alt', 'page_group_id' => 4, 'is_active' => true],
            ['controller' => 'AltOrdemTipoPg', 'method' => 'altOrdemTipoPg', 'menu_controller' => 'alt-ordem-tipo-pg', 'menu_method' => 'alt-ordem-tipo-pg', 'page_name' => 'Alterar Ordem Tipo Página', 'notes' => '<p>Página para alterar a ordem do tipo de páginas.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'Situacao', 'method' => 'listar', 'menu_controller' => 'situacao', 'menu_method' => 'listar', 'page_name' => 'Situação', 'notes' => '<p>Página para listar as situações.</p>', 'is_public' => false, 'icon' => 'fas fa-exclamation-triangle', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'VerSit', 'method' => 'verSit', 'menu_controller' => 'ver-sit', 'menu_method' => 'ver-sit', 'page_name' => 'Ver Situações', 'notes' => '<p>Página para ver detalhes da situações.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'CadastrarSit', 'method' => 'cadSit', 'menu_controller' => 'cadastrar-sit', 'menu_method' => 'cad-sit', 'page_name' => 'Cadastrar Situações', 'notes' => '<p>Formulário para cadastrar situações.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'EditarSit', 'method' => 'editSit', 'menu_controller' => 'editar-sit', 'menu_method' => 'edit-sit', 'page_name' => 'Editar as Situações', 'notes' => '<p>Formulário para editar a Situações.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'ApagarSit', 'method' => 'apagarSit', 'menu_controller' => 'apagar-sit', 'menu_method' => 'apagar-sit', 'page_name' => 'Apagar Situações', 'notes' => '<p>Página para apagar situações.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'SituacaoUser', 'method' => 'listar', 'menu_controller' => 'situacao-user', 'menu_method' => 'listar', 'page_name' => 'Situações dos Usuários', 'notes' => '<p>Listar as situações de usuário.</p>', 'is_public' => false, 'icon' => 'far fa-id-badge', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'VerSitUser', 'method' => 'verSitUser', 'menu_controller' => 'ver-sit-user', 'menu_method' => 'ver-sit-user', 'page_name' => 'Ver Situações de Usuário', 'notes' => '<p>Pá¡gina para ver detalhes da situações de usuário.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'CadastrarSitUser', 'method' => 'cadSitUser', 'menu_controller' => 'cadastrar-sit-user', 'menu_method' => 'cad-sit-user', 'page_name' => 'Cadastrar Situações de Usuário', 'notes' => '<p>Página para cadastrar situações de usuário.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'EditarSitUser', 'method' => 'editSitUser', 'menu_controller' => 'editar-sit-user', 'menu_method' => 'edit-sit-user', 'page_name' => 'Editar Situaçõµes de Usuário', 'notes' => '<p>Formulário para editar situações de usuário.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'ApagarSitUser', 'method' => 'apagarSitUser', 'menu_controller' => 'apagar-sit-user', 'menu_method' => 'apagar-sit-user', 'page_name' => 'Apagar Situações de Usuário', 'notes' => '<p>Página para apagar situações de usuário.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 4, 'is_active' => true],
            ['controller' => 'SituacaoPg', 'method' => 'listar', 'menu_controller' => 'situacao-pg', 'menu_method' => 'listar', 'page_name' => 'Situações de Página', 'notes' => '<p>Listar as situações de páginas.</p>', 'is_public' => false, 'icon' => 'fas fa-exclamation', 'page_group_id' => 1, 'is_active' => true],
            ['controller' => 'VerSitPg', 'method' => 'verSitPg', 'menu_controller' => 'ver-sit-pg', 'menu_method' => 'ver-sit-pg', 'page_name' => 'Ver Situações de Página', 'notes' => '<p>Página para ver detalhes da situações de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 5, 'is_active' => true],
            ['controller' => 'CadastrarSitPg', 'method' => 'cadSitPg', 'menu_controller' => 'cadastrar-sit-pg', 'menu_method' => 'cad-sit-pg', 'page_name' => 'Cadastrar Situações de Página', 'notes' => '<p>Formulário para cadastrar situações de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 2, 'is_active' => true],
            ['controller' => 'EditarSitPg', 'method' => 'editSitPg', 'menu_controller' => 'editar-sit-pg', 'menu_method' => 'edit-sit-pg', 'page_name' => 'Editar situações de página', 'notes' => '<p>Formulário para editar situações de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 3, 'is_active' => true],
            ['controller' => 'ApagarSitPg', 'method' => 'apagarSitPg', 'menu_controller' => 'apagar-sit-pg', 'menu_method' => 'apagar-sit-pg', 'page_name' => 'Apagar Situação da Página', 'notes' => '<p>Página para apagar situação de página.</p>', 'is_public' => false, 'icon' => '', 'page_group_id' => 4, 'is_active' => true],
        ];

        foreach ($pages as $page) {
            DB::table('pages')->updateOrInsert(
                ['controller' => $page['controller'], 'method' => $page['method']],
                [
                    'menu_controller' => $page['menu_controller'],
                    'menu_method' => $page['menu_method'],
                    'page_name' => $page['page_name'],
                    'notes' => $page['notes'],
                    'is_public' => $page['is_public'],
                    'icon' => $page['icon'],
                    'page_group_id' => $page['page_group_id'],
                    'is_active' => $page['is_active'],
                    'created_at' => $now,
                    'updated_at' => null,
                ]
            );
        }
    }
}
