<?php

namespace App\Notifications;

use App\Models\Vacancy;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Enviada para recrutadores (usuários com MANAGE_VACANCIES) quando o
 * listener CreateSubstitutionVacancyFromDismissal cria automaticamente
 * uma vaga a partir de um desligamento com open_vacancy=true.
 *
 * Canais: mail + database (igual pattern do Helpdesk). Database permite
 * aparecer no inbox/sino do frontend; mail garante que alguém do DP veja
 * mesmo fora do sistema.
 */
class VacancyAutoGeneratedNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(public Vacancy $vacancy) {}

    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $this->vacancy->loadMissing(['store', 'position', 'replacedEmployee', 'originMovement']);

        $employeeName = $this->vacancy->replacedEmployee?->name ?? '(sem informação)';
        $storeCode = $this->vacancy->store_id ?? '-';
        $positionName = $this->vacancy->position?->name ?? '-';
        $forecast = $this->vacancy->delivery_forecast?->format('d/m/Y') ?? '-';

        return (new MailMessage)
            ->subject("Nova vaga gerada automaticamente — {$positionName} ({$storeCode})")
            ->greeting("Olá, {$notifiable->name}")
            ->line("Uma vaga de substituição foi criada automaticamente a partir do desligamento de **{$employeeName}**.")
            ->line("**Loja:** {$storeCode}")
            ->line("**Cargo:** {$positionName}")
            ->line("**Prazo previsto:** {$forecast} ({$this->vacancy->predicted_sla_days} dias de SLA)")
            ->line('A vaga está aberta em rascunho. Atribua um recrutador e avance o status quando possível.')
            ->action('Abrir vaga', url("/vacancies?status=open"))
            ->line('Esta é uma notificação automática do módulo de Abertura de Vagas.');
    }

    public function toDatabase(object $notifiable): array
    {
        $this->vacancy->loadMissing(['store', 'position', 'replacedEmployee']);

        return [
            'type' => 'vacancy_auto_generated',
            'vacancy_id' => $this->vacancy->id,
            'store_id' => $this->vacancy->store_id,
            'store_name' => $this->vacancy->store?->name,
            'position_id' => $this->vacancy->position_id,
            'position_name' => $this->vacancy->position?->name,
            'replaced_employee_id' => $this->vacancy->replaced_employee_id,
            'replaced_employee_name' => $this->vacancy->replacedEmployee?->name,
            'origin_movement_id' => $this->vacancy->origin_movement_id,
            'delivery_forecast' => $this->vacancy->delivery_forecast?->toDateString(),
            'predicted_sla_days' => $this->vacancy->predicted_sla_days,
        ];
    }
}
