<?php

namespace App\Listeners;

use App\Enums\Permission;
use App\Events\PersonnelMovementCreated;
use App\Models\PersonnelMovement;
use App\Models\User;
use App\Models\Vacancy;
use App\Notifications\VacancyAutoGeneratedNotification;
use App\Services\VacancyIntegrationService;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Notification;

/**
 * Escuta PersonnelMovementCreated e, se o movimento for um desligamento
 * com a flag open_vacancy=true, cria uma vaga de substituição em rascunho
 * (status=open) via VacancyIntegrationService::suggestVacancyForDismissal.
 *
 * Síncrono por simplicidade — a criação da vaga é parte do mesmo fluxo de
 * criação do movimento e precisa estar disponível imediatamente na listagem
 * de vagas para o DP.
 */
class CreateSubstitutionVacancyFromDismissal
{
    public function __construct(
        protected VacancyIntegrationService $integrationService,
    ) {}

    public function handle(PersonnelMovementCreated $event): void
    {
        $movement = $event->movement;

        if ($movement->type !== PersonnelMovement::TYPE_DISMISSAL) {
            return;
        }

        if (! $movement->open_vacancy) {
            return;
        }

        try {
            $vacancy = $this->integrationService->suggestVacancyForDismissal($movement);

            if ($vacancy instanceof Vacancy) {
                $this->notifyRecruiters($vacancy);
            }
        } catch (\Throwable $e) {
            // Falha aqui não deve bloquear a criação do movimento. A vaga
            // pode ser criada manualmente depois pelo DP referenciando o
            // movimento. Log para diagnóstico.
            Log::warning('Failed to auto-create substitution vacancy from dismissal', [
                'movement_id' => $movement->id,
                'employee_id' => $movement->employee_id,
                'error' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Dispara VacancyAutoGeneratedNotification para todos os usuários com
     * permissão MANAGE_VACANCIES. A notificação vai por mail + database
     * (inbox/sino). Falhas individuais no envio NÃO devem quebrar o fluxo
     * do listener — já estamos dentro do try do handle(), mas isolamos
     * ainda mais log-ando aqui por clareza de diagnóstico.
     */
    protected function notifyRecruiters(Vacancy $vacancy): void
    {
        $recruiters = User::all()
            ->filter(fn (User $u) => $u->hasPermissionTo(Permission::MANAGE_VACANCIES))
            ->values();

        if ($recruiters->isEmpty()) {
            return;
        }

        try {
            Notification::send($recruiters, new VacancyAutoGeneratedNotification($vacancy));
        } catch (\Throwable $e) {
            Log::warning('Failed to notify recruiters about auto-generated vacancy', [
                'vacancy_id' => $vacancy->id,
                'recipient_count' => $recruiters->count(),
                'error' => $e->getMessage(),
            ]);
        }
    }
}
