<?php

/**
 * Module definitions for the SaaS platform.
 *
 * Each module maps to route groups, permissions, and menu sections.
 * Used by CheckTenantModule middleware and MenuService to control access.
 */

return [
    'dashboard' => [
        'name' => 'Dashboard',
        'description' => 'Painel principal com indicadores e métricas.',
        'routes' => ['dashboard'],
        'icon' => 'HomeIcon',
    ],
    'users' => [
        'name' => 'Usuários',
        'description' => 'Gestão de usuários do sistema.',
        'routes' => ['users.*'],
        'icon' => 'UserGroupIcon',
    ],
    'employees' => [
        'name' => 'Funcionários',
        'description' => 'Cadastro e gestão de funcionários, contratos e histórico.',
        'routes' => ['employees.*'],
        'icon' => 'IdentificationIcon',
    ],
    'stores' => [
        'name' => 'Lojas',
        'description' => 'Gestão de lojas e unidades.',
        'routes' => ['stores.*'],
        'icon' => 'BuildingStorefrontIcon',
    ],
    'sales' => [
        'name' => 'Vendas',
        'description' => 'Registro e consulta de vendas.',
        'routes' => ['sales.*'],
        'icon' => 'CurrencyDollarIcon',
    ],
    'products' => [
        'name' => 'Produtos',
        'description' => 'Catálogo de produtos e variantes.',
        'routes' => ['products.*'],
        'icon' => 'CubeIcon',
    ],
    'transfers' => [
        'name' => 'Transferências',
        'description' => 'Transferências entre lojas.',
        'routes' => ['transfers.*'],
        'icon' => 'ArrowsRightLeftIcon',
    ],
    'stock_adjustments' => [
        'name' => 'Ajustes de Estoque',
        'description' => 'Ajustes e correções de estoque.',
        'routes' => ['stock-adjustments.*'],
        'icon' => 'ClipboardDocumentListIcon',
    ],
    'order_payments' => [
        'name' => 'Ordens de Pagamento',
        'description' => 'Solicitações e controle de pagamentos.',
        'routes' => ['order-payments.*'],
        'icon' => 'BanknotesIcon',
    ],
    'suppliers' => [
        'name' => 'Fornecedores',
        'description' => 'Cadastro de fornecedores.',
        'routes' => ['suppliers.*'],
        'icon' => 'TruckIcon',
    ],
    'purchase_orders' => [
        'name' => 'Ordens de Compra',
        'description' => 'Gestão de ordens de compra de coleções com state machine, recebimento e integração com estoque.',
        'routes' => ['purchase-orders.*'],
        'icon' => 'ShoppingCartIcon',
        'dependencies' => ['suppliers', 'stores'],
    ],
    'checklists' => [
        'name' => 'Checklists',
        'description' => 'Checklists de qualidade.',
        'routes' => ['checklists.*'],
        'icon' => 'ClipboardDocumentCheckIcon',
    ],
    'medical_certificates' => [
        'name' => 'Atestados Médicos',
        'description' => 'Controle de atestados médicos.',
        'routes' => ['medical-certificates.*'],
        'icon' => 'DocumentTextIcon',
    ],
    'absences' => [
        'name' => 'Faltas',
        'description' => 'Controle de faltas de funcionários.',
        'routes' => ['absences.*'],
        'icon' => 'CalendarDaysIcon',
    ],
    'overtime' => [
        'name' => 'Horas Extras',
        'description' => 'Controle de horas extras.',
        'routes' => ['overtime-records.*'],
        'icon' => 'ClockIcon',
    ],
    'work_shifts' => [
        'name' => 'Jornadas de Trabalho',
        'description' => 'Definição de jornadas de trabalho.',
        'routes' => ['work-shifts.*'],
        'icon' => 'CalendarIcon',
    ],
    'work_schedules' => [
        'name' => 'Escalas de Trabalho',
        'description' => 'Escalas e quadros de horários.',
        'routes' => ['work-schedules.*'],
        'icon' => 'TableCellsIcon',
    ],
    'menus' => [
        'name' => 'Menus',
        'description' => 'Gestão de menus do sistema.',
        'routes' => ['menus.*'],
        'icon' => 'Bars3Icon',
    ],
    'pages' => [
        'name' => 'Páginas',
        'description' => 'Gestão de páginas e grupos.',
        'routes' => ['pages.*', 'page-groups.*'],
        'icon' => 'DocumentIcon',
    ],
    'access_levels' => [
        'name' => 'Níveis de Acesso',
        'description' => 'Configuração de permissões por nível.',
        'routes' => ['access-levels.*'],
        'icon' => 'ShieldCheckIcon',
    ],
    'color_themes' => [
        'name' => 'Temas de Cores',
        'description' => 'Personalização visual.',
        'routes' => ['color-themes.*'],
        'icon' => 'SwatchIcon',
    ],
    'activity_logs' => [
        'name' => 'Logs de Atividade',
        'description' => 'Histórico de ações no sistema.',
        'routes' => ['activity-logs.*'],
        'icon' => 'ClipboardDocumentListIcon',
    ],
    'user_sessions' => [
        'name' => 'Usuários Online',
        'description' => 'Monitoramento de sessões ativas.',
        'routes' => ['user-sessions.*'],
        'icon' => 'SignalIcon',
    ],
    'config' => [
        'name' => 'Configurações',
        'description' => 'Tabelas de configuração do sistema.',
        'routes' => ['config.*'],
        'icon' => 'CogIcon',
    ],
    'integrations' => [
        'name' => 'Integrações',
        'description' => 'Integrações com sistemas externos (CIGAM, SAP, etc.).',
        'routes' => ['integrations.*'],
        'icon' => 'LinkIcon',
    ],
    'store_goals' => [
        'name' => 'Metas de Loja',
        'description' => 'Definição e acompanhamento de metas por loja.',
        'routes' => ['store-goals.*'],
        'icon' => 'ChartBarIcon',
    ],
    'movements' => [
        'name' => 'Movimentações',
        'description' => 'Movimentações diárias de estoque sincronizadas do CIGAM.',
        'routes' => ['movements.*'],
        'icon' => 'ArrowPathIcon',
    ],
    'vacations' => [
        'name' => 'Férias',
        'description' => 'Solicitação, aprovação e controle de férias.',
        'routes' => ['vacations.*'],
        'icon' => 'SunIcon',
        'dependencies' => ['employees'],
    ],
    'stock_audits' => [
        'name' => 'Auditoria de Estoque',
        'description' => 'Inventário com contagem, conciliação CIGAM e relatórios.',
        'routes' => ['stock-audits.*'],
        'icon' => 'ClipboardDocumentCheckIcon',
        'dependencies' => ['products', 'stores'],
    ],
    'personnel_movements' => [
        'name' => 'Movimentação de Pessoal',
        'description' => 'Gestão de movimentações: desligamento, promoção, transferência e reativação.',
        'routes' => ['personnel-movements.*'],
        'icon' => 'ArrowsUpDownIcon',
        'dependencies' => ['employees'],
    ],
    'vacancies' => [
        'name' => 'Abertura de Vagas',
        'description' => 'Gestão de vagas abertas: substituição, aumento de quadro e volante. Ciclo completo até pré-cadastro do contratado.',
        'routes' => ['vacancies.*'],
        'icon' => 'BriefcaseIcon',
        'dependencies' => ['employees', 'personnel_movements'],
    ],
    'training' => [
        'name' => 'Treinamentos',
        'description' => 'Gestão de treinamentos, eventos de capacitação, facilitadores e certificados.',
        'routes' => ['trainings.*', 'training-contents.*', 'training-content-categories.*', 'training-courses.*', 'my-trainings.*', 'training-reports.*', 'training-quizzes.*', 'training-quiz-attempts.*'],
        'icon' => 'AcademicCapIcon',
        'dependencies' => ['employees', 'stores'],
    ],
    'experience-tracker' => [
        'name' => 'Avaliação de Experiência',
        'description' => 'Acompanhamento do período de experiência (45/90 dias).',
        'routes' => ['experience-tracker.*'],
        'icon' => 'ClipboardDocumentCheckIcon',
        'dependencies' => ['employees', 'stores'],
    ],
    'delivery' => [
        'name' => 'Entregas',
        'description' => 'Gestão de entregas, rotas de motoristas e manifesto.',
        'routes' => ['deliveries.*', 'delivery-routes.*', 'driver-dashboard.*'],
        'icon' => 'TruckIcon',
        'dependencies' => ['stores'],
    ],
    'chat' => [
        'name' => 'Chat',
        'description' => 'Mensagens diretas, grupos e comunicados em tempo real.',
        'routes' => ['chat.*'],
        'icon' => 'ChatBubbleLeftRightIcon',
        'dependencies' => ['users'],
    ],
    'helpdesk' => [
        'name' => 'Helpdesk',
        'description' => 'Sistema de chamados com SLA, departamentos e relatórios.',
        'routes' => ['helpdesk.*', 'helpdesk-reports.*'],
        'icon' => 'LifebuoyIcon',
        'dependencies' => ['users'],
    ],
    'taneia' => [
        'name' => 'TaneIA',
        'description' => 'Assistente virtual de inteligência artificial (microsserviço Python).',
        'routes' => ['taneia.*'],
        'icon' => 'SparklesIcon',
        'dependencies' => ['users'],
    ],
    'reversals' => [
        'name' => 'Estornos',
        'description' => 'Solicitações de estorno de vendas (total ou parcial) com workflow de aprovação, integração CIGAM e hook Helpdesk.',
        'routes' => ['reversals.*'],
        'icon' => 'ArrowUturnLeftIcon',
        'dependencies' => ['movements', 'stores'],
    ],
    'returns' => [
        'name' => 'Devoluções',
        'description' => 'Solicitações de troca, devolução e crédito do e-commerce. Workflow de 6 estados com logística reversa.',
        'routes' => ['returns.*'],
        'icon' => 'ArrowPathRoundedSquareIcon',
        'dependencies' => ['movements', 'stores'],
    ],
    'cost_centers' => [
        'name' => 'Centros de Custo',
        'description' => 'Cadastro de centros de custo com hierarquia — fundação para orçamentos e DRE.',
        'routes' => ['cost-centers.*'],
        'icon' => 'Squares2X2Icon',
    ],
    'accounting_classes' => [
        'name' => 'Plano de Contas',
        'description' => 'Plano de contas contábil com grupos DRE — fundação dos relatórios gerenciais e orçamentos.',
        'routes' => ['accounting-classes.*'],
        'icon' => 'DocumentChartBarIcon',
    ],
    'management_classes' => [
        'name' => 'Plano Gerencial',
        'description' => 'Plano de contas gerencial — visão interna operacional, complementar ao plano contábil.',
        'routes' => ['management-classes.*'],
        'icon' => 'FolderOpenIcon',
        'dependencies' => ['accounting_classes', 'cost_centers'],
    ],
    'budgets' => [
        'name' => 'Orçamentos',
        'description' => 'Orçamento anual por escopo com versionamento e consumo previsto × realizado.',
        'routes' => ['budgets.*'],
        'icon' => 'BanknotesIcon',
        'dependencies' => ['accounting_classes', 'management_classes', 'cost_centers'],
    ],
    'coupons' => [
        'name' => 'Cupons',
        'description' => 'Cadastro e solicitação de cupons de desconto para Consultores, Influencers e MS Indica. Fluxo de emissão em duas etapas (solicitação → emissão do código pelo e-commerce).',
        'routes' => ['coupons.*'],
        'icon' => 'TicketIcon',
        'dependencies' => ['employees', 'stores'],
    ],
    'dre' => [
        'name' => 'DRE Gerencial',
        'description' => 'Demonstrativo do Resultado do Exercício — matriz executiva com realizado × orçado × ano anterior, mapeamento conta contábil → linha gerencial e fechamento de períodos.',
        'routes' => ['dre.*'],
        'icon' => 'ChartBarIcon',
        'dependencies' => ['accounting_classes', 'cost_centers'],
    ],
    'consignments' => [
        'name' => 'Consignações',
        'description' => 'Controle de consignações (Cliente, Influencer, E-commerce). Vinculação obrigatória com catálogo de produtos e notas fiscais do CIGAM (movement_code 20 saída / 21 retorno), validação de itens de retorno e bloqueio por inadimplência.',
        'routes' => ['consignments.*'],
        'icon' => 'ArchiveBoxArrowDownIcon',
        'dependencies' => ['products', 'employees', 'stores'],
    ],
];
